class Hoge < ApplicationRecord
end

# クラスメソッド
:defined_enums
:attribute_type_decorations
:_validators
:configurations
:connection_handler
:pluralize_table_names
:table_name_suffix
:_validate_callbacks
:_validate_callbacks=
:_validators?
:_attr_readonly
:_attr_readonly=
:index_nested_attribute_errors
:_attr_readonly?
:primary_key_prefix_type
:table_name_prefix=
:table_name_suffix=
:schema_migrations_table_name=
:internal_metadata_table_name
:logger
:internal_metadata_table_name=
:pluralize_table_names=
:pluralize_table_names?
:index_nested_attribute_errors=
:_reflections?
:aggregate_reflections?
:attributes_to_define_after_schema_loads?
:attribute_type_decorations?
:lock_optimistically
:lock_optimistically=
:defined_enums=
:include_root_in_json?
:table_name_prefix
:__callbacks=
:include_root_in_json
:include_root_in_json=
:local_stored_attributes
:lock_optimistically?
:__callbacks?
:_validation_callbacks
:_validation_callbacks=
:_initialize_callbacks
:defined_enums?
:_initialize_callbacks=
:_find_callbacks
:_find_callbacks=
:after_find
:_touch_callbacks
:_touch_callbacks=
:after_touch
:local_stored_attributes=
:_save_callbacks
:_save_callbacks=
:primary_key_prefix_type=
:table_name_prefix?
:table_name_suffix?
:schema_format
:schema_format=
:error_on_ignored_order
:error_on_ignored_order=
:error_on_ignored_order_or_limit
:error_on_ignored_order_or_limit=
:timestamped_migrations=
:dump_schema_after_migration
:dump_schema_after_migration=
:dump_schemas
:dump_schemas=
:warn_on_records_fetched_greater_than=
:default_connection_handler
:connection_handler=
:default_connection_handler=
:schema_migrations_table_name?
:internal_metadata_table_name?
:store_full_sti_class
:store_full_sti_class=
:store_full_sti_class?
:default_scopes
:default_scope_override
:default_scopes=
:logger=
:default_scope_override=
:cache_timestamp_format
:around_save
:after_save
:_update_callbacks
:_create_callbacks
:_create_callbacks=
:before_create
:around_create
:before_save
:_destroy_callbacks
:_destroy_callbacks=
:_update_callbacks=
:before_update
:timestamped_migrations
:after_update
:attribute_method_matchers?
:after_create
:_reflections
:before_destroy
:around_destroy
:after_destroy
:around_update
:skip_time_zone_conversion_for_attributes=
:time_zone_aware_types
:schema_migrations_table_name
:nested_attributes_options?
:skip_time_zone_conversion_for_attributes?
:time_zone_aware_types?
:skip_time_zone_conversion_for_attributes
:attribute_aliases?
:partial_writes=
:attribute_aliases
:attribute_method_matchers
:attribute_aliases=
:attribute_method_matchers=
:time_zone_aware_types=
:partial_writes
:nested_attributes_options=
:cache_timestamp_format=
:cache_timestamp_format?
:default_connection_handler?
:maintain_test_schema
:maintain_test_schema=
:_validators=
:nested_attributes_options
:_rollback_callbacks
:time_zone_aware_attributes
:time_zone_aware_attributes=
:default_timezone
:default_timezone=
:_before_commit_callbacks
:_commit_callbacks=
:_commit_callbacks
:partial_writes?
:attribute_type_decorations=
:_before_commit_callbacks=
:_before_commit_without_transaction_enrollment_callbacks
:warn_on_records_fetched_greater_than
:configurations=
:_commit_without_transaction_enrollment_callbacks=
:_before_commit_without_transaction_enrollment_callbacks=
:_rollback_callbacks=
:_rollback_without_transaction_enrollment_callbacks
:_rollback_without_transaction_enrollment_callbacks=
:_commit_without_transaction_enrollment_callbacks
:record_timestamps
:record_timestamps=
:_reflections=
:aggregate_reflections=
:belongs_to_required_by_default
:belongs_to_required_by_default=
:aggregate_reflections
:record_timestamps?
:attributes_to_define_after_schema_loads
:attributes_to_define_after_schema_loads=
:__callbacks
:after_initialize
:suppress
:has_secure_token
:generate_unique_secure_token
:store
:stored_attributes
:store_accessor
:_store_accessors_module
:reflect_on_all_autosave_associations
:reflect_on_all_aggregations
:clear_reflections_cache
:reflections
:reflect_on_aggregation
:reflect_on_all_associations
:reflect_on_association
:_reflect_on_association
:no_touching
:before_commit
:before_commit_without_transaction_enrollment
:after_create_commit
:after_update_commit
:after_destroy_commit
:after_commit
:transaction
:after_rollback
:after_commit_without_transaction_enrollment
:after_rollback_without_transaction_enrollment
:composed_of
:accepts_nested_attributes_for
:has_secure_password
:belongs_to
:has_many
:has_one
:has_and_belongs_to_many
:touch_attributes_with_time
:serialize
:primary_key
:reset_primary_key
:get_primary_key
:quoted_primary_key
:primary_key=
:instance_method_already_implemented?
:dangerous_attribute_method?
:define_attribute_methods
:undefine_attribute_methods
:method_defined_within?
:dangerous_class_method?
:class_method_defined_within?
:attribute_method?
:has_attribute?
:attribute_names
:initialize_generated_modules
:column_for_attribute
:attribute_method_affix
:generated_attribute_methods
:attribute_alias?
:attribute_alias
:define_attribute_method
:alias_attribute
:attribute_method_prefix
:attribute_method_suffix
:after_validation
:before_validation
:locking_enabled?
:locking_column
:update_counters
:locking_column=
:reset_locking_column
:decorate_attribute_type
:decorate_matching_attribute_types
:define_attribute
:attribute
:increment_counter
:reset_counters
:decrement_counter
:validates_uniqueness_of
:validates_presence_of
:validates_length_of
:validates_associated
:validates_size_of
:validates_absence_of
:validates_confirmation_of
:validates_numericality_of
:validates_inclusion_of
:validates_format_of
:validates_exclusion_of
:validates_acceptance_of
:set_callbacks
:skip_callback
:reset_callbacks
:define_callbacks
:normalize_callback_params
:__update_callbacks
:get_callbacks
:set_callback
:define_model_callbacks
:validates!
:validators
:validate
:validates_each
:validates_with
:clear_validators!
:validators_on
:validates
:to_param
:_to_partial_path
:scope
:all
:default_scoped
:scope_for_association
:default_extensions
:scope_attributes?
:unscoped
:before_remove_const
:scope_attributes
:current_scope
:current_scope=
:sti_name
:base_class
:abstract_class
:compute_type
:descends_from_active_record?
:new
:abstract_class?
:abstract_class=
:finder_needs_type_condition?
:table_name=
:reset_column_information
:full_table_name_prefix
:full_table_name_suffix
:yaml_encoder
:reset_sequence_name
:sequence_name=
:next_sequence_value
:column_defaults
:content_columns
:sequence_name
:table_name
:quoted_table_name
:table_exists?
:column_names
:_default_attributes
:inheritance_column
:columns
:columns_hash
:attribute_types
:protected_environments
:type_for_attribute
:protected_environments=
:inheritance_column=
:ignored_columns
:ignored_columns=
:attributes_builder
:initialize_load_schema_monitor
:reset_table_name
:prefetch_primary_key?
:attr_readonly
:readonly_attributes
:create!
:instantiate
:create
:find_by
:find_by!
:arel_table
:inspect
:allocate
:===
:type_caster
:initialize_find_by_cache
:generated_association_methods
:arel_engine
:arel_attribute
:predicate_builder
:find
:collection_cache_key
:relation_delegate_class
:initialize_relation_delegate_cache
:enum
:collecting_queries_for_explain
:exec_explain
:lookup_ancestors
:i18n_scope
:human_attribute_name
:offset
:except
:many?
:pluck
:take!
:first!
:last!
:second!
:third!
:fourth!
:fifth!
:forty_two!
:third_to_last!
:second_to_last!
:first_or_create
:first_or_create!
:first_or_initialize
:find_or_create_by
:find_or_create_by!
:find_or_initialize_by
:last
:update_all
:destroy
:destroy_all
:find_in_batches
:third
:fourth
:fifth
:forty_two
:third_to_last
:second_to_last
:reorder
:find_each
:delete_all
:in_batches
:rewhere
:joins
:left_joins
:left_outer_joins
:where
:limit
:create_with
:having
:find_by_sql
:extending
:unscope
:count_by_sql
:preload
:group
:delete
:none
:exists?
:readonly
:calculate
:count
:order
:eager_load
:includes
:select
:or
:lock
:maximum
:distinct
:from
:average
:first
:update
:any?
:one?
:none?
:merge
:ids
:second
:take
:references
:minimum
:sum
:uncached
:cache
:connection_specification_name
:connection_specification_name=
:connection_config
:connection_pool
:clear_all_connections!
:retrieve_connection
:connected?
:clear_cache!
:clear_active_connections!
:clear_reloadable_connections!
:remove_connection
:establish_connection
:sqlite3_connection
:connection
:direct_descendants
:descendants
:benchmark
:model_name
:yaml_tag
:subclasses
:superclass
:class_attribute
:json_creatable?
:pretty_print
:mattr_reader
:parent_name
:cattr_reader
:mattr_writer
:cattr_writer
:included_modules
:include?
:name
:ancestors
:attr
:attr_reader
:attr_writer
:attr_accessor
:instance_methods
:public_instance_methods
:protected_instance_methods
:private_instance_methods
:constants
:const_get
:const_set
:const_defined?
:class_variables
:remove_class_variable
:class_variable_get
:class_variable_set
:class_variable_defined?
:public_constant
:private_constant
:deprecate_constant
:singleton_class?
:autoload
:include
:module_exec
:module_eval
:class_eval
:class_exec
:remove_method
:undef_method
:method_defined?
:<
:alias_method
:>
:private_class_method
:protected_method_defined?
:public_method_defined?
:private_method_defined?
:public_instance_method
:public_class_method
:thread_cattr_reader
:cattr_accessor
:mattr_accessor
:thread_mattr_accessor
:instance_method
:define_method
:delegate
:thread_mattr_reader
:autoload?
:thread_mattr_writer
:deprecate
:thread_cattr_accessor
:thread_cattr_writer
:rake_extension
:parent
:remove_possible_method
:remove_possible_singleton_method
:attr_internal_reader
:attr_internal_writer
:attr_internal_accessor
:attr_internal
:<=>
:<=
:>=
:==
:freeze
:prepend
:redefine_method
:parents
:anonymous?
:reachable?
:to_s
:method_visibility
:pretty_print_cycle
:delegate_missing_to
:unloadable
:guess_for_anonymous
:const_missing
:concerning
:concern
:to_json
:to_yaml
:duplicable?
:in?
:presence_in
:acts_like?
:with_options
:as_json
:instance_values
:instance_variable_names
:`
:blank?
:present?
:to_query
:html_safe?
:deep_dup
:presence
:pretty_print_inspect
:pretty_print_instance_variables
:require_or_load
:load_dependency
:require_dependency
:try!
:try
:instance_variable_defined?
:remove_instance_variable
:instance_of?
:kind_of?
:is_a?
:tap
:instance_variable_get
:instance_variable_set
:protected_methods
:instance_variables
:private_methods
:method
:public_method
:public_send
:singleton_method
:byebug
:define_singleton_method
:remote_byebug
:debugger
:extend
:to_enum
:enum_for
:pretty_inspect
:=~
:!~
:gem
:eql?
:respond_to?
:object_id
:send
:display
:class
:nil?
:hash
:dup
:singleton_class
:clone
:then
:itself
:yield_self
:untaint
:taint
:tainted?
:trust
:untrust
:untrusted?
:singleton_methods
:frozen?
:methods
:public_methods
:equal?
:!
:instance_exec
:!=
:instance_eval
:__id__
:__send__



# インスタンスメソッド
:updated_at
:id_came_from_user?
:id_changed?
:id_change
:id_will_change!
:id_previously_changed?
:id_previous_change
:restore_id!
:saved_change_to_id?
:saved_change_to_id
:id_before_last_save
:will_save_change_to_id?
:id_change_to_be_saved
:created_at=
:created_at_before_type_cast
:created_at_came_from_user?
:created_at?
:created_at_changed?
:created_at_change
:created_at_will_change!
:created_at_was
:created_at_previously_changed?
:created_at_previous_change
:restore_created_at!
:created_at
:saved_change_to_created_at?
:saved_change_to_created_at
:created_at_before_last_save
:will_save_change_to_created_at?
:created_at_change_to_be_saved
:created_at_in_database
:updated_at=
:updated_at_before_type_cast
:updated_at_came_from_user?
:updated_at?
:updated_at_changed?
:updated_at_change
:updated_at_will_change!
:updated_at_was
:updated_at_previously_changed?
:updated_at_previous_change
:restore_updated_at!
:saved_change_to_updated_at?
:saved_change_to_updated_at
:updated_at_before_last_save
:will_save_change_to_updated_at?
:updated_at_change_to_be_saved
:updated_at_in_database
:pluralize_table_names
:table_name_suffix
:_validate_callbacks
:_validators?
:index_nested_attribute_errors
:_reflections
:primary_key_prefix_type
:pluralize_table_names?
:logger
:model_name
:_reflections?
:aggregate_reflections?
:include_root_in_json
:lock_optimistically
:defined_enums
:table_name_prefix
:include_root_in_json?
:lock_optimistically?
:__callbacks?
:_validation_callbacks
:_initialize_callbacks
:defined_enums?
:_find_callbacks
:_run_touch_callbacks
:_touch_callbacks
:_run_save_callbacks
:_save_callbacks
:cache_timestamp_format
:table_name_prefix?
:table_name_suffix?
:schema_format
:error_on_ignored_order
:store_full_sti_class
:error_on_ignored_order_or_limit
:_create_callbacks
:dump_schema_after_migration
:_run_update_callbacks
:dump_schemas
:nested_attributes_options
:_run_create_callbacks
:default_connection_handler
:_update_callbacks
:_destroy_callbacks
:_run_destroy_callbacks
:attribute_aliases?
:store_full_sti_class?
:default_scopes
:default_scope_override
:attribute_method_matchers?
:column_for_attribute
:_run_initialize_callbacks
:timestamped_migrations
:_run_find_callbacks
:nested_attributes_options?
:skip_time_zone_conversion_for_attributes
:time_zone_aware_types
:skip_time_zone_conversion_for_attributes?
:time_zone_aware_types?
:partial_writes
:attribute_aliases
:attribute_method_matchers
:_run_before_commit_without_transaction_enrollment_callbacks
:_run_before_commit_callbacks
:_run_commit_without_transaction_enrollment_callbacks
:cache_timestamp_format?
:default_connection_handler?
:_run_commit_callbacks
:_run_rollback_callbacks
:_run_rollback_without_transaction_enrollment_callbacks
:validation_context
:_validators
:_rollback_callbacks
:time_zone_aware_attributes
:_before_commit_callbacks
:default_timezone
:_run_validate_callbacks
:_commit_callbacks
:partial_writes?
:_before_commit_without_transaction_enrollment_callbacks
:_commit_without_transaction_enrollment_callbacks
:warn_on_records_fetched_greater_than
:_rollback_without_transaction_enrollment_callbacks
:record_timestamps
:record_timestamps=
:aggregate_reflections
:record_timestamps?
:_run_validation_callbacks
:__callbacks
:type_for_attribute
:to_global_id
:to_gid
:to_signed_global_id
:to_sgid
:to_gid_param
:to_sgid_param
:save!
:save
:serializable_hash
:from_json
:as_json
:read_attribute_for_serialization
:touch_later
:no_touching?
:touch
:rollback_active_record_state!
:before_committed!
:committed!
:rolledback!
:with_transaction_returning_status
:add_to_transaction
:transaction
:destroy
:reload
:_destroy
:mark_for_destruction
:destroyed_by_association=
:changed_for_autosave?
:marked_for_destruction?
:destroyed_by_association
:association
:association_cached?
:increment!
:attribute_was
:raw_write_attribute
:changes_internally_applied
:changes_applied
:attribute_in_database
:clear_changes_information
:clear_attribute_changes
:changed_attributes
:previous_changes
:saved_change_to_attribute?
:saved_change_to_attribute
:attribute_before_last_save
:saved_changes?
:saved_changes
:will_save_change_to_attribute?
:attribute_change_to_be_saved
:changes_to_save
:changed_attribute_names_to_save
:attributes_in_database
:attribute_change
:attribute_changed?
:changed?
:changed
:has_changes_to_save?
:attribute_changed_in_place?
:changes
:attribute_previously_changed?
:restore_attributes
:attributes_changed_by_setter
:to_key
:id_in_database
:id
:id=
:id?
:id_before_type_cast
:id_was
:query_attribute
:attributes_before_type_cast
:read_attribute_before_type_cast
:write_attribute
:read_attribute
:_read_attribute
:[]
:[]=
:has_attribute?
:attribute_for_inspect
:respond_to?
:attribute_present?
:attribute_names
:accessed_fields
:attributes
:respond_to_without_attributes?
:attribute_missing
:method_missing
:lock!
:with_lock
:locking_enabled?
:valid?
:validate
:validates_length_of
:validates_confirmation_of
:validates_size_of
:validates_numericality_of
:validates_inclusion_of
:validates_presence_of
:validates_format_of
:validates_exclusion_of
:validates_absence_of
:validates_acceptance_of
:run_callbacks
:errors
:invalid?
:validates_with
:read_attribute_for_validation
:validate!
:cache_key
:to_param
:to_partial_path
:to_model
:attributes=
:assign_attributes
:quoted_id
:initialize_internals_callback
:populate_with_current_scope_attributes
:destroy!
:becomes
:delete
:becomes!
:new_record?
:persisted?
:update_attribute
:update!
:update_attributes
:update_attributes!
:update_column
:update_columns
:decrement!
:toggle
:toggle!
:update
:increment
:decrement
:destroyed?
:connection_handler
:pretty_print
:<=>
:freeze
:inspect
:hash
:==
:readonly!
:init_with
:slice
:readonly?
:frozen?
:eql?
:encode_with
:to_json
:to_yaml
:duplicable?
:in?
:presence_in
:acts_like?
:with_options
:instance_values
:instance_variable_names
:`
:blank?
:present?
:to_query
:html_safe?
:deep_dup
:presence
:pretty_print_cycle
:pretty_print_inspect
:pretty_print_instance_variables
:unloadable
:require_or_load
:load_dependency
:require_dependency
:try!
:try
:instance_variable_defined?
:remove_instance_variable
:instance_of?
:kind_of?
:is_a?
:tap
:instance_variable_get
:instance_variable_set
:protected_methods
:instance_variables
:private_methods
:method
:public_method
:public_send
:singleton_method
:byebug
:class_eval
:define_singleton_method
:remote_byebug
:debugger
:extend
:to_enum
:enum_for
:pretty_inspect
:===
:=~
:!~
:gem
:object_id
:send
:to_s
:display
:class
:nil?
:dup
:singleton_class
:clone
:then
:itself
:yield_self
:untaint
:taint
:tainted?
:trust
:untrust
:untrusted?
:singleton_methods
:methods
:public_methods
:equal?
:!
:instance_exec
:!=
:instance_eval
:__id__
:__send__
